### PR TITLE
Add httr for correct use of user_agent method

### PR DESCRIPTION
**Pull request by MarcusKlik**
Hi @phillc73, you assembled a great collection of space API's! I could install the package with a small change in moonData.R. Nice to see there are more space-fans out there :-)

### CODE REVIEW

**Comment by phillc73** [comment]
Thanks very much for that! This was a toy project born of too much red wine and Iain M. Banks last winter. It's nice to know someone else has actually looked at it. Appreciate the pull request.

**Comment by MarcusKlik** [comment]
Ha! In that case I must say your coding skills are quite good while on red wine 👍

**Comment by phillc73** [comment]
Multiple offline edits before committing (usually the next day). 

You've inspired me to have another look at it now though. Maybe write some proper documentation.

**Comment by MarcusKlik** [comment]
that's good :-) I see that for modest use you can also use the `DEMO_KEY`, for example to look at these pretty amazing satellite images:

https://api.nasa.gov/EPIC/archive/enhanced/2016/12/04/png/epic_RBG_20161204003633_01.png?api_key=DEMO_KEY

perhaps you can set the `DEMO_KEY` as a default, so that package users can start using the API's immediately after downloading!

**Pull request merged**
